#ifndef IOCONFIG_H
#define IOCONFIG_H

#define Ser1_TX 0
#define Ser1_RX 1
#define Ser2_TX 4
#define Ser2_RX 5
#define SERIAL_SPEED (24*9600)

#define MIDI_CABLE_NAME_1 "C1"
#define MIDI_CABLE_NAME_2 "C2"
#define MIDI_CABLE_NAME_3 "C3"

#define MAX_CMD_SIZE (256+128)

#define AUDIO_SAMPLE_RATE 24000
#define AUDIO_SAMPLE_MILLIS 1000
#define AUDIO_BUFFER_SIZE (AUDIO_SAMPLE_RATE * AUDIO_SAMPLE_MILLIS / 1000)

#define SEQ_SLOT_NUM 256
#define ACTIVE_ENVELOPE_NUM 256

#endif